### ISSUE TITLE
出现错误，麻烦看看怎么回事

### ISSUE THREAD

**Issue by yyc727** [rmlzy/export-jd-read#8] opened 2021-11-19 10:44 UTC
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! export_jd_read@5.0.0 start: `node ./src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the export_jd_read@5.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-19T10_32_05_348Z-debug.log

[2021-11-19T10_32_05_348Z-debug.log](https://github.com/rmlzy/export-jd-read/files/7569677/2021-11-19T10_32_05_348Z-debug.log)
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@6.14.11
3 info using node@v10.24.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle export_jd_read@5.0.0~prestart: export_jd_read@5.0.0
6 info lifecycle export_jd_read@5.0.0~start: export_jd_read@5.0.0
7 verbose lifecycle export_jd_read@5.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle export_jd_read@5.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/export-jd-read/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle export_jd_read@5.0.0~start: CWD: /root/export-jd-read
10 silly lifecycle export_jd_read@5.0.0~start: Args: [ '-c', 'node ./src/index.js' ]
11 silly lifecycle export_jd_read@5.0.0~start: Returned: code: 1  signal: null
12 info lifecycle export_jd_read@5.0.0~start: Failed to exec start script
13 verbose stack Error: export_jd_read@5.0.0 start: `node ./src/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid export_jd_read@5.0.0
15 verbose cwd /root/export-jd-read
16 verbose Linux 4.18.0-305.25.1.el8_4.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v10.24.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error export_jd_read@5.0.0 start: `node ./src/index.js`
22 error Exit status 1
23 error Failed at the export_jd_read@5.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by rmlzy** [comment] 2021-11-22 08:01
linux 环境吗? 安装依赖的时候有报错吗?

**Comment by yyc727** [comment] 2021-11-22 08:09
现在解决了，看了大家提的问题，结果是没有输出文件夹，在文件夹没新建输出文件夹就解决了，建议增加此步奏。另外能否输出pdf格式的文件的选择，可以根据自身需要选择，感谢大佬的无私奉献与耐心答复！

发自我的iPhone

**Comment by rmlzy** [comment] 2021-11-22 08:45
感谢你的反馈, 这个问题已修复

我最近闲下来会支持输出 PDF 格式
Duplicate of #https://github.com/rmlzy/export-jd-read/issues/4

**Closed by rmlzy** 2021-11-22 08:45 UTC

**Comment by yyc727** [comment] 2021-11-22 10:59
再次表示感谢和支持！！！

发自我的iPhone
